fix Required `json` property not found
Error: Required `json` property not found.
    at Object.module.exports.parse (/Users/art/.nvm/versions/node/v8.9.0/lib/node_modules/api-console-cli/node_modules/api-console-dev-preview/node_modules/raml2obj/index.js:39:27)
    at JsonGenerator.enhance (/Users/art/.nvm/versions/node/v8.9.0/lib/node_modules/api-console-cli/node_modules/api-console-dev-preview/node_modules/raml-js-data-provider/node_modules/raml-json-enhance-node/lib/json-generator.js:90:24)
    at parse.then (/Users/art/.nvm/versions/node/v8.9.0/lib/node_modules/api-console-cli/node_modules/api-console-dev-preview/node_modules/raml-js-data-provider/node_modules/raml-json-enhance-node/lib/json-generator.js:60:26)
    at <anonymous>